---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-nat-vpp
spec:
  template:
    spec:
      containers:
        - name: nse
          volumeMounts:
            - mountPath: /etc/nat/config.yaml
              subPath: config.yaml
              name: nat-config-volume
      volumes:
        - name: nat-config-volume
          configMap:
            name: nat-config-file
